### ISSUE TITLE
Backup Restores not working consistently

### ISSUE THREAD

**Issue by bscott** [standardnotes/desktop#665] opened 2021-02-25 06:02 UTC
Hello,

I have an extended membership under Email 1, I export an encrypted backup with 512 notes. I create a fresh new SN account without Extended Membership and import my recent backup to email 2, the total notes are 428, not 512. This number changes every time I try and import it into a fresh account and very reproducible. 

2nd Issue, after I import into my NON extended account, I click the extensions button and it shows my new email as Extended with my 2FA token being required with an expiration date of my actual membership on email 1, even so, I never attached my extended membership to this new account Email 2 via the Extended Dashboard and never setup 2FA auth on this new account. 

I have several screen captures if needed of this full flow in action. 

Last tested on Web v3.5.19 & Desktop v3.5.18

**Comment by JaspalSuri** [comment] 2021-02-25 11:34
Hi @bscott,

I was able to reproduce this issue and had around 100 missing items as well; thanks for bringing it to our attention! 

One workaround that I've tested is to import the notes locally before signing in and syncing them to your account. Please let us know if this works for you. 

As for the second issue, the exported backups are quite comprehensive, so it appears to be working as intended. 🙂

**Comment by bscott** [comment] 2021-02-26 08:49
Hi @JaspalSuri 

I started up SN NOT signed in and made sure I cleared the local cache. I imported my backup of 526 Notes. The import only completed 328 notes out of the 526.

**Comment by JaspalSuri** [comment] 2021-02-26 10:26
Hi @bscott,

I'm sorry to hear that; this is the first time that I've heard of the workaround not helping. I've tested it on the web (v3.5.19) and desktop (v.3.5.18) apps on macOS Big Sur.

Here are the steps that I used:

1. Export an encrypted backup from the desktop or [web app](app.standardnotes.org)
2. Open the desktop app or the [web app](app.standardnotes.org)
3. Sign out if currently signed in
4. Without signing in, click on the **Account** menu on the lower left of the app and click on **Import Backup** to import your notes' backup file into the app
5. Either sign into an existing account (that has been cleared out) or create a new account (for testing purposes and optionally [delete](https://standardnotes.org/reset) it or the old account later):
5a. Click on **Sign In**, enter your account's credentials, and make sure the **Merge Local Data** option is selected
5b. Click on **Register**, set a username, password, confirm the password, and make sure the **Merge Local Data** option is selected
6. After being signed in, verify that all of your notes were synced to your account

(The credit for these steps goes to an anonymous user who emailed them to us; I've edited them somewhat for this comment.)

**Comment by bscott** [comment] 2021-03-04 06:00
@JaspalSuri I did not try a fresh cleaned out account, I will try that

**Comment by bscott** [comment] 2021-03-10 08:13
@JaspalSuri so my situation is getting worse, I logged in today after 24hrs. Every Theme, Action & Editor is duplicated 5 times. On top of that my notes have duplicated 3X and I didn't even import any backup. Overnight, I now have 1035 Notes when yesterday I had 525.

**Comment by JaspalSuri** [comment] 2021-03-11 14:12
Hi @bscott, I'm so sorry to hear that. 🙁 

Just to make sure, by _logging in_, you're referring to explicitly signing in and not launching the app while already signed in, correct? 

Also which OS and browser were you using?

Can you DM us your notes syncing account username on Slack or email it to us at help@standardnotes.org or standardnotes@protonmail.com with a link to this thread? 

For what it's worth regarding issues with the Batch Manager, we plan to replace it with something better. 🙂

**Comment by bscott** [comment] 2021-03-11 16:48
Thanks @JaspalSuri 

To clearify, I logged completely out of the app.

I'll send the details over DM

Thank you

**Comment by JaspalSuri** [comment] 2021-03-12 12:22
Thank you for elaborating, @bscott. I am awaiting the DM. 🙂 I've created a preliminary report for the dev team to review in the meantime.

**Comment by bscott** [comment] 2021-03-12 16:14
Oh thought I sent it, I'll send again @JaspalSuri

**Comment by JaspalSuri** [comment] 2021-05-21 09:13
Hello again @bscott,

SNJS, the (standalone, and soon the included) [decrypt script](https://standardnotes.org/offline), and web/desktop apps have been updated to properly decrypt CloudLink backups. The issue with duplicate and unassociated tags has been addressed in a separate fix as well. 

Thank you so much for helping us test this and for the initial report. 🙂

**Closed by JaspalSuri** 2021-05-21 09:13 UTC
