### ISSUE TITLE
Sort 'by title' doesn't work at startup

### ISSUE THREAD

**Issue by MustachedMario** [standardnotes/desktop#334] opened 2019-04-24 09:06 UTC
- Sorting 'by title' doesnt work directly after startup the SN desktop app, for the view "all notes".
- By clicking on an tag/view, sorting works as expected.
- Using the latest SN Version 3.0.8

**Comment by mobitar** [comment] 2019-04-24 12:28
Hmm can't replicate this. Is this while data is loading, or after everything has loaded? Can you provide step-by-step instructions to replicate, and see if it also happens in the web app?

**Comment by MustachedMario** [comment] 2019-04-24 13:27
So here are the steps to reproduce.
- Fresh & clean install of SN 3.0.8 (Windows User Profile also cleaned from SN files)
- Open SN Desktop and sign in
- The sorting of "All Notes" are defaulted to "Date added" i think.
- Change the sorting to "Title".
- Clicking through some tags and see that sorting by "Title" works as expected.
- Restarting the desktop app, per default, the "all notes" view is selected automaticly
- **At this point, "all notes" are sorted by Date or something.**
- Clicking again to some other view/tags, this comes to the expected "title" sorting.

BTW: This also happends to the Web App.

**Comment by PunnyBoi** [comment] 2019-04-25 07:39
Well, I observe that after restarting SN, the notes are still arranged by the user-defined sorting except that the notes are now in a descending manner rather than ascending. I think only the windows version has this issue.

**Comment by mobitar** [comment] 2019-04-25 12:32
I tested on the web app but can't seem to replicate this. It might be an account related issue, given that user preferences are saved per account. How many notes do you have total?

**Comment by MustachedMario** [comment] 2019-04-25 14:40
Currently my total note count is about 20.
Still testing how to get "feature parity" with mobile app, with a minimal extension set.

In my case, the inital sort seems to be "date added" and not like PunnyBoi's case, "descending".
It seems, that "pinned" notes shows also at startup, even i set the filter to not showing pinned notes.
The pinned notes disapear after i change the view fore/back.
So can this be an issue with "Pinned" notes?

**Comment by PunnyBoi** [comment] 2019-04-26 06:59
I can confirm this for windows version but can't replicate for the web version. I guess @MustachedMario is facing this issue on windows.

**Comment by MustachedMario** [comment] 2019-04-26 07:18
Yeah, I'am using the windows version, but this happends on webversion too.
There is also a minimal chance, that the sorting works corretly at start. (~30 Starts, 1-2x correct sorting).
On mobile (ios), the sorting was always correct.

**Comment by mobitar** [comment] 2019-04-26 12:49
> The pinned notes disapear after i change the view fore/back.
    So can this be an issue with "Pinned" notes?

The problem seems to be that user preferences are properly loaded, but not reflected in the UI for some reason. This sounds like a race condition, which means reproducing it will be tricky.

User preferences are an item stored in your data, like any other item, such as a note or tag. One thing we can try is deleting the user preferences object from your account, and letting the app re-create it when you sign back in. If you'd like me to try this, shoot me an email at mo@standardnotes.org from your account email. Otherwise, you can do this manually by exporting your account data, opening the resulting .txt file, finding the JSON item with content_type "SN|UserPreferences", removing it, then importing the file back into a new account (or same account, if you [reset](https://standardnotes.org/reset) it and re-create it).

Ideally we'd just fix this issue, but without more user reports this sounds like it will be near impossible to replicate on my end.

**Comment by MustachedMario** [comment] 2019-04-26 15:14
I try a restet later ...
So far, i extracted the UserPreferences part and it looks good to me.

> {
  "references": [],
  "appData": {
    "org.standardnotes.sn": {
      "client_updated_at": "2019-04-25T14:53:22.762Z",
      "tagsPanelWidth": 216,
      "marginResizersEnabled": false,
      "notesPanelWidth": 419,
      "editorWidth": null,
      "editorLeft": 0,
      "hideNotePreview": false,
      "sortReverse": false,
      "spellcheck": false,
      "showArchived": false,
      "monospaceFont": true,
      "sortBy": "title",
      "hideDate": false,
      "hidePinned": false
    }
  }
}

**Comment by MustachedMario** [comment] 2019-04-27 07:02
Before i reset my account, i tested it again with a fresh test account.
I create 10 notes, set the sorting to "title", quit, restart, and the sorting was also false.
I also test this again with the webversion with the same results.
Maybe this is a regional/language stuff problem?

BTW:
When the webversion is loading, you can see for a very short time (~250ms), that the sorting is set by "date added" until the all stuff is finished loading and ends up to "title". And in my case, the wrong sorting looks like "date added".

**Comment by mobitar** [comment] 2019-04-27 14:01
Wait so in your test account, does it end up with Title after the 250ms delay? And Title is the desired sort right?

**Comment by MustachedMario** [comment] 2019-04-27 15:45
Yep, i see 250ms "date added", then is see "title" as my sort (as i prefer), but the result is not sorting to "title", but "date added".

**Comment by mobitar** [comment] 2019-04-28 13:36
So the UI shows sorting by "Title", but the actual list of notes do not appear to be sorted by title? In that case, is this a different issue from the original issue, or it's the same issue you originally described?

**Comment by MustachedMario** [comment] 2019-04-28 13:55
Its the same issue. The initial list sort after starting the windows desktop & web version is wrong, but UI shows "title".

So this excatly happens on desktop and web (but it's easier to see on web version):
- desktop/web is loading the whole UI with empty taglist and notes list
- at this time i can see the sorting is set to "date added" (default value i think)
- around 250ms passed so far
- then the user notes/preferences are fully loaded, tagslist are filled and my sorting is set "title"
- notes list is filled, but sorted to "date added" (UI shows still "title")

**Comment by mobitar** [comment] 2019-04-29 13:53
Any chance you can capture a video of this? Sometimes there are small details that can be much better captured by a video than text. Still having a tough time replicating this..

**Comment by MustachedMario** [comment] 2019-04-29 18:51
I created a video @60fps from loading the web version.
There are only 6 frames with changes, so i extracted them and create a GIF with 3sec delay each frame.
(**Note**: I created the demo notes in this order: bbb, ccc, aaa, ddd)

What you will see:
1. Emtpy screen
2. UI is loaded with default settings ("date added")
3. Tags loaded from users account
4. Notes loaded from users account
5. User settings loaded from account ("title", custom pane size)
6. First note gets the focus.
7. Wrong inital sorting of notes pane

![SN-WebAppStartSlowMotion-ResultsInWrongInitialSorting](https://user-images.githubusercontent.com/10989798/56918673-ecc25500-6abe-11e9-8e8e-f9f1c40c710e.gif)

**Comment by mobitar** [comment] 2019-04-30 13:56
Hmm interesting. Thanks for the gif. Can you share the credentials for this test account so I can try logging into it? Feel free to create another one if the email identifies you, or you can email me the credentials as well to mo@standardnotes.org.

**Comment by MustachedMario** [comment] 2019-05-05 19:30
Just FYI.
I seen a strange behavior with the wrong inital sorting, that triggers the correct sorting.

- Look at the last frame of the GIF above, when the top note gets the focus.
- Now change anything with this focused note, e.g. add/remove a single letter
- "Saving..." is triggered and the "All notes" pane refreshes automaticly with the correct sorting (by 'title'.)

Maybe this helps with further investigations.

**Comment by mobitar** [comment] 2019-05-06 13:50
I've received a similar report with sorting, but in this case, it was imported data and all items had the same "created at" date, so sorting those could result in different orders each time. Hopefully we get a little more clues over time.

**Comment by MustachedMario** [comment] 2019-05-07 19:53
I don't wan't to bother you, just FYI...
Just changing the theme from statusbar, does also triggers the correct sorting.

**Comment by mobitar** [comment] 2019-05-14 15:01
I believe I've identified the issue, and the fix will be included in the next desktop/web release (3.0.9).

**Comment by MustachedMario** [comment] 2019-05-18 11:20
I can confirm, that v3.0.9 fix this issue on windows desktop app and web version.
The mobile version never had this problem, at least on my phone.

Thanks for fixing.

**Comment by mobitar** [comment] 2019-05-18 13:54
Ok great!

**Closed by mobitar** 2019-05-18 13:54 UTC
