### ISSUE TITLE
Desktop app cannot be used offline

### ISSUE THREAD

**Issue by kaumanns** [standardnotes/desktop#18] opened 2017-01-18 13:48 UTC
Currently, the main window just stays blank if there is no internet connection.

The reason seems to be that the main index.html points to remote JavaScript and CSS code.
This implementation is also mentioned as problematic in [that issue](https://github.com/standardnotes/desktop/issues/10). 

Awesome work BTW! Love the philosophy behind it. A minimalist encrypted cross-platform notes app like this one is long needed.

**Comment by mobitar** [comment] 2017-01-18 13:51
Thanks, glad you like it :) Getting the remote JS issue fixed is #1 priority right now. Will update this issue as soon as it's fixed.

**Comment by kaumanns** [comment] 2017-01-18 13:54
Note: You mentioned on hackernews that the desktop app is supposed to work offline. Did not work for me on Macos Sierra at least, just FYI.

**Comment by mobitar** [comment] 2017-01-18 13:55
Right, I was assuming the app was already open or cached, in which case it would work online. Totally failed to consider the remote JS issue. But after that, it should work offline as intended.

**Comment by kaumanns** [comment] 2017-01-18 13:55
Cool! Thanks for all your hard work.

**Comment by threkk** [comment] 2017-01-23 15:48
Is there any expected ETA for the fix of this issue?

**Comment by mobitar** [comment] 2017-01-23 15:58
I would say about 1-2 weeks. I have to set up an Electron auto-update server before I can remove the remote JS.

**Comment by mobitar** [comment] 2017-01-31 17:58
Fixed in latest release: https://github.com/standardnotes/desktop/releases/

**Closed by mobitar** 2017-01-31 17:58 UTC
