### ISSUE TITLE
Feature: Biometrics for login

### ISSUE THREAD

**Issue by RonanCodes** [standardnotes/desktop#764] opened 2021-09-22 17:39 UTC
Currently you have to type your password each time on MacOS, there is no biometric option:
<img width="419" alt="Screenshot 2021-09-22 at 18 37 47" src="https://user-images.githubusercontent.com/6930753/134393748-917ce735-df38-45c7-be90-6b12c526cfef.png">

Can we add in touch id as a login option?

**Comment by JaspalSuri** [comment] 2021-09-23 07:17
Hi @RonanCodes, thanks for the suggestion. 🙂 It's something that's a part of our long-term roadmap. 

I'm going to close this thread since it's a duplicate of [this one](https://github.com/standardnotes/forum/issues/927).

**Closed by JaspalSuri** 2021-09-23 07:17 UTC
Labels: duplicate, enhancement
