### ISSUE TITLE
Windows app extensions not working

### ISSUE THREAD

**Issue by SEmhof** [standardnotes/desktop#323] opened 2019-02-22 18:20 UTC
I am using the desktop app on Windows 8.1 at my workplace.  I am unable to get themes, tags or editors other than the Plain Editor to work.

1) Tags do not appear at top of the screen underneath the note (though they do appear in the All notes list on the left-hand side if I have assigned notes via the iOS app or my home computer running Windows 10).

2) Changing editors just gives me a blank screen.

3) Changing themes makes no visible changes.

In the console I get the following errors:
![standard notes console errors](https://user-images.githubusercontent.com/13921900/53262443-6b4be200-368b-11e9-83b4-c256c0db8685.PNG)

I do not encounter any of these errors on my home workstation or on either the iphone or ipad app.

**Comment by mobitar** [comment] 2019-02-23 16:00
Hmm, it looks like offline installation of extensions have failed completely, so the app is trying to access files that don't exist. What kind of restrictions does your workplace environment impose on what files you can save? Are you allowed to write to the directory you see (AppData/Roaming/Standard Notes/...)?

The desktop app should fallback to the web hosted version of extensions if the local files don't load, but this may not be working properly if you're seeing this. I may have to investigate that to see if there has been a regression. While we investigate this, I recommend using the web app at app.standardnotes.org, where your extensions should load properly.

**Comment by MustachedMario** [comment] 2019-02-24 11:37
I have the absolute same Problem. I am sure, that this is an issue with corporate proxy. 
Authentification / Single Sign on is done correctly, because Standard Note Desktop App can Auth against  Standard Note Server, can load all Notes, but fail to load Extensions.
I do not investigate where Extensions are load from (url /port /etc.), but i am sure this happens, because extensions are not loaded the same way as the notes from the web.

**Comment by mobitar** [comment] 2019-02-25 16:47
In the desktop app, extensions are loaded from disk, so we would need read-write access to AppDir/Extensions, where AppDir can be found via Help -> Open Data Directory. Can you check if any files exist in the Extensions directory?

**Comment by SEmhof** [comment] 2019-02-25 18:14
Selecting Data Directory takes me to [user]/AppData/Roaming/Standard Notes

In the Extensions folder there is a folder named "downloads"

Inside there are zip files of the themes I've installed.  If I try to open one (open, not extract) I get this error:

![standard notes theme error](https://user-images.githubusercontent.com/13921900/53358690-de509500-38e5-11e9-9f4b-0303b639b2f1.PNG)

The zip files all have the same Date Modified date, which corresponds to the time I opened up the desktop version of Standard Notes on my workstation:

![standard notes file mod date](https://user-images.githubusercontent.com/13921900/53358776-0dff9d00-38e6-11e9-8f30-d28fc82fa1c6.PNG)

**Comment by mobitar** [comment] 2019-02-26 18:30
Hmm, so that's the issue there. The application is able to download the extension files, but is unable to unzip them and actually install them. I wonder why it's able to actually save the zip files, but not open them. Can you try to see if you can place an arbitrary file or folder in that directory and see if it lets you?

**Comment by MustachedMario** [comment] 2019-02-26 19:11
@mobitar 
look at the filesize of the zips, 0 bytes, so they are unzippable.
All zip files only exists during runtime of SN. After closing SN, all zips are gone.
This is why i believe, that this zips a downloaded in an other way, then the rest.

**Comment by SEmhof** [comment] 2019-02-26 19:44
Yes, I was able to save a file into both the Extensions and downloads folders

**Comment by mobitar** [comment] 2019-02-27 17:22
Hmm, indeed, the file sizes are 0. Strange. Definitely seems to be a permissions issue. Can you try uninstalling the app, then re-installing it? When you uninstall, you should delete the data directory as well (including the Extensions folder). Perhaps that will correct the permissions.

After re-install, take a look at this same directory, and see if the zip files have a proper size.

**Comment by SEmhof** [comment] 2019-02-27 17:44
Uninstalled; deleted data directory and reinstalled.  The zip files are the same: showing up, but 0 KB.

**Comment by MustachedMario** [comment] 2019-02-27 18:08
I did another test. I connected my workplace notebook to a pure internet connection and SN is able to download an use these extensions. So this problem must be an issue with corporate proxy and SN.
The proxy has no restriction, execpt using single-sign on for auth instead of using user/pass.

**Comment by mobitar** [comment] 2019-02-28 15:29
@SEmhof thanks for confirming. @MustachedMario ah yeah, the desktop app doesn't currently support proxy configs. Something I hope to add in the near future.

**Comment by mobitar** [comment] 2019-04-18 15:01
3.0.8 will better handle this error when it occurs (so this way you don't just get a white screen).

**Closed by mobitar** 2019-04-18 15:01 UTC
