### ISSUE TITLE
Tags sorting on Tags panel 

### ISSUE THREAD

**Issue by sancho-one** [standardnotes/desktop#100] opened 2017-10-09 20:04 UTC
It seems that tags aren't sorted at Tags panel at all. Expected behavior: sort tags alphabetically.

![screenshot from 2017-10-09 15-02-12](https://user-images.githubusercontent.com/32115115/31356275-1445a4f4-ad03-11e7-8801-bab34cb6f4fc.png)

**Comment by mobitar** [comment] 2017-10-09 20:28
Thanks, it should be sorting. Might be a regression. I'll take a look.

**Comment by sancho-one** [comment] 2017-10-09 20:48
@mobitar I've noticed very interesting effect: this problem goes away once SN App is restarted. So when you're working actively with tags (renaming etc, deleted them, etc) you have tag sorting broken, but it autofixes on program restart.

**Comment by mobitar** [comment] 2017-10-09 20:48
Yup, it looks like tags are sorted on load, but if you add a new tag, it's placed at the top. I've fixed this and it will be released with the v2 release sometime this week.

**Comment by sancho-one** [comment] 2017-10-09 20:49
@mobitar exactly, I've come to the same conclusion! ;)

**Closed** 2017-10-16 15:00 UTC

**Comment by sancho-one** [comment] 2017-10-16 16:57
Unfortunatelly, in 2.0 beta tags added during the current session still are at the top until SN Desktop restarted.

**Comment by mobitar** [comment] 2017-10-16 16:58
That's strange. I'm looking at right now and it's functioning properly. Try downloading the official v2 release: https://standardnotes.org/download/all

**Comment by sancho-one** [comment] 2017-10-16 17:00
My version's 2.0.0-beta 3. Re-download?

**Comment by mobitar** [comment] 2017-10-16 17:00
Yup

**Comment by sancho-one** [comment] 2017-10-16 17:01
Ok, I'll write you back soon.

**Comment by sancho-one** [comment] 2017-10-16 17:04
It's very strange, but the version I've just downloaded doesn't want to start, here's console output:

./appimagetool-x86_64.AppImage 
WARNING: appstreamcli is missing, please install it if you want to use AppStream metadata
SOURCE is missing

**Comment by sancho-one** [comment] 2017-10-16 17:06
At the same time standard-notes-2.0.0-beta3-x86_64.AppImage is running perfectly fine...

**Comment by mobitar** [comment] 2017-10-16 17:07
What's the full filename of the version you downloaded?

**Comment by sancho-one** [comment] 2017-10-16 17:15
Oh no, I've forgotten to move from Downloads to bin. Fixed. Everything is OK now. I confirm that tags are sorted in the real-time!

**Comment by mobitar** [comment] 2017-10-16 17:15
Ok great!
