### ISSUE TITLE
Feature request: Minimize / close to tray

### ISSUE THREAD

**Issue by Andrewskiz** [standardnotes/desktop#155] opened 2018-02-20 19:40 UTC
Hi, it would be nice to be able to close the desktop application to the system tray.

**Comment by mobitar** [comment] 2018-02-21 18:12
Hi @Andrewskiz, can you describe this a little more? I'm a Mac user so can't be sure what OS you're referring to. Windows?

**Comment by leafcutterant** [comment] 2018-11-20 18:16
Duplicate of more encompassing issue #103, request for closing.

**Closed** 2018-11-21 16:00 UTC
