### ISSUE TITLE
Update from appimage doesn't work

### ISSUE THREAD

**Issue by popey** [standardnotes/desktop#438] opened 2019-11-20 19:52 UTC
Disclaimer: I am an advocate for snaps, and even provided #250 to enable snap support. So feel free to take my feedback with a pinch of salt, as I may be seen as biased. However, my feedback is meant honestly as a user.

Platform: Ubuntu 19.10. Standard Notes from AppImage.

Standard Notes is the only appimage I have on my system, and updates break *every* time. 

Long time Standard Notes user and advocate. I love it. But the update mechanism via appimage is just broken. Every time I get an update notification, I click the relevant menu item. Standard Notes closes, and doesn't restart. I have found a downloaded appimage file, but the icon in my launcher is now broken.

I had to remove the icon from my launcher, make the AppImage file executable, launch it and then re-add it to my launcher. 

This is a completely user hostile process for updating software. Please consider supporting other ways to update the software. Thanks.

**Comment by mobitar** [comment] 2019-11-20 21:24
Yeah...given the [changes](https://github.com/standardnotes/desktop/issues/430) to AppImages no longer being fully "self-contained", we might finally have to explore alternative options.

**Comment by aaantoszek** [comment] 2019-11-22 06:23
Snaps are really cool user-wise

**Comment by aden-young** [comment] 2019-12-02 14:06
I've had the same update experience as @popey has explained here, and I can confirm it is frustrating.

+1 to the idea of using a snap package, this would automate the update process, and would allow standardnotes to be featured on the de-facto Linux app store (Simplenote could use some good competition there):
https://snapcraft.io/store

**Comment by shockinghobby** [comment] 2019-12-04 05:19
Use AppImageLauncher. It's does pretty much the same as snapd without tying you to a store.

**Comment by baptiste-grob** [comment] 2020-04-14 08:21
Closing this as we publish the app on [Snapcraft](https://snapcraft.io/standard-notes) nowadays :)

**Closed by baptiste-grob** 2020-04-14 08:21 UTC

**Comment by r3l4t1v** [comment] 2020-04-15 09:29
Should this issue really be closed? The problem is still there: updating from AppImages doesn't work.

Fair enough if the project has decided to go with snaps, though I hope that flatpaks were/are considered as well. Flatpak is pretty popular outside of the Ubuntu world :)
