### ISSUE TITLE
Can't drag credentials via 1Password

### ISSUE THREAD

**Issue by grub-basket** [standardnotes/desktop#465] opened 2020-01-11 23:38 UTC
Instead a message about needing to use FileSafe with the Bold editor appears. The credentials must be copied and pasted or typed in. Is there a way to deactivate it when the account button/window has been clicked/toggled? 
![Prompt](https://user-images.githubusercontent.com/12993901/72211942-a6fcbf80-3488-11ea-87d8-cb28361e63de.png)

I am using macOS and the latest version of SN, as of two days ago.

**Comment by PaulBGD** [comment] 2020-02-07 00:45
This happens when any text is dragged in, would be nice if the prompt didn't come up when this happens

**Comment by mobitar** [comment] 2020-02-07 15:35
This will be fixed in upcoming 3.3 release :)

**Comment by baptiste-grob** [comment] 2020-03-10 12:07
3.3 is out so I'm closing this issue but feel free to reopen it if the problem is still there @grub-basket!

**Closed by baptiste-grob** 2020-03-10 12:07 UTC
