### ISSUE TITLE
[Windows] Tags counter disapears from left sidebar

### ISSUE THREAD

**Issue by MustachedMario** [standardnotes/desktop#361] opened 2019-06-20 10:21 UTC
Since V3.0.14, all tags counters disapears from the left sidebar, until you click on the sidebars separator. You don't have to resize the sidebar, just click on the separator.

**Comment by mobitar** [comment] 2019-06-20 16:11
Hmm..can you click Help > Toggle Error Console, and show what errors it displays in red when you see this issue?

**Comment by MustachedMario** [comment] 2019-06-20 20:28
I'm not sure i am using the console correctly, but it seems there is no error.

If i looking to the html, the following line has no value:
`<div class="count ng-binding"></div>`
until i click on the seperator (div id="resizer-overlay"), the value was filled
`<div class="count ng-binding">4</div>`

**Comment by mobitar** [comment] 2019-06-21 14:12
Hmm you may be viewing the wrong tab. Be sure to click the Console tab.

**Comment by MustachedMario** [comment] 2019-06-24 18:25
Sorry for late response...

They are absolute no error or warnings in the Console.
I'am playing a bit with the UI and the hidden tag counters are shown not only by clicking the separator, there are also shown by changing the theme or click "unlock" note etc. This looks similar to the already fixed "wrong title sorting at startup" problem, because UI seems to be not rendered/processed completely at startup. I don't mean the visuals, more like that the last window events are not processed.

**Comment by mobitar** [comment] 2019-06-26 14:17
Right, the problem is that a UI refresh cycle needs to occur, and that usually occurs when you interact with the UI in any way. But this refresh should trigger programmatically when tags are ready. I'll have to wait on more user reports. Do you see this issue in the web app as well?

**Comment by MustachedMario** [comment] 2019-06-26 14:19
Nope, the web version works as it should, at least with firefox.

**Comment by MustachedMario** [comment] 2019-06-30 12:00
Now, this happens also to the web version with firefox.
Maybe there was some stuff cached before from old version.
Currently, i see V3.0.15 in firefox.

**Comment by mobitar** [comment] 2019-07-01 14:53
And still nothing in the console when this happens?

**Comment by MustachedMario** [comment] 2019-07-01 15:08
No, console is empty. But, on my workplace pc, with firefox, the tag counter are displayed in the
web version. This is strange. (Could not test the desktop version, because SN doesn't support proxys).

Could this be a problem with hardware acceleration?
Because this workplace pc is so old, hardware acceleration isn't supported by firefox.
All my problems so far with SN seems related to refreshing problems (hidden tag counter, title sorting) caused by modern hardware?
As far as I know, firefox and electron are able to use hardware acceleration, if detected.

**Comment by mobitar** [comment] 2019-07-01 15:10
I saw this issue before a recent release, but patched it quickly. You must have found another edge case that triggers it. So I don't believe it's hardware based. I just don't have any other leads currently as to what it can be.

**Comment by MustachedMario** [comment] 2019-07-07 10:08
Are any serverside changes made? Because the tag counters are displayed on desktop and web the last 1-2 days without any flaws on different computers.

**Comment by mobitar** [comment] 2019-07-08 14:31
Nope. 3.0.15 was the last release on June 25.

**Comment by MustachedMario** [comment] 2019-09-09 18:12
FYI. This still happens on V3.0.16.

**Comment by MustachedMario** [comment] 2020-02-05 18:56
FYI.
Since V3.3 (Web, I don't use Desktop anymore), this issue seems to be solved, BUT, wrong sorting of notes after start (e.g. by title), is back.
Well, this isn't funny anymore.

**Comment by mobitar** [comment] 2020-02-06 15:47
> BUT, wrong sorting of notes after start (e.g. by title), is back.

Can you describe this more?

**Comment by MustachedMario** [comment] 2020-02-07 08:50
Look at this: https://github.com/standardnotes/desktop/issues/334

**Comment by baptiste-grob** [comment] 2020-04-14 08:24
Closing the issue as the original problem has been resolved

**Closed** 2020-04-14 08:23 UTC
